config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # CRUDを全て作成する。
  resources :timetables do
    resources :stages, shallow: true do
      resources :artists, shallow: true
    end
  end

  resources :timetables, only: [ :show ] do
    resources :artists
  end

  # rootパスを設定する
  root "timetables#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full overflow-hidden">

<head>
    <title><%= content_for(:title) || "Everyones Timetable" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "material_symbols", "data-turbo-track": "reload" %>

    <%# Material Symbols の追加 %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=person" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body class="h-full overflow-hidden">
    <nav class="flex items-center h-12 bg-white border-b border-gray-100">
        <div class=" w-full mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center">
                <div class="flex">
                    <%= link_to "みんなのタイムテーブル", root_path, class: "inline-flex items-center text-sm text-gray-800 hover:text-gray-700 font-bold transition-colors duration-150" %>
                </div>
                <div class="flex items-center space-x-4">
                    <% unless authenticated? %>
                    <%= link_to "ログイン", new_session_path, class: "inline-flex items-center text-sm font-bold text-gray-800 hover:text-gray-400 transition-colors duration-150" %>
                    <% else %>
                    <%# ユーザーメニュー %>
                    <div class="relative" data-controller="dropdown">
                        <button type="button" class="flex justify-center items-center gap-x-1 text-sm font-bold text-gray-800 hover:text-gray-600" data-action="click->dropdown#toggle">
                            <%# Googleマテリアル person %>
                            <span class="material-symbols-outlined">person</span>
                        </button>

                        <div class="absolute right-0 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden z-[160]" data-dropdown-target="menu">
                            <%= link_to "アカウント", "#", class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
                            <div class="border-t border-gray-100"></div>
                            <%= button_to "ログアウト", session_path, method: :delete, class: "block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-red-50 hover:text-red-700" %>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </nav>

    <main class="h-full">
        <%= yield %>
    </main>
</body>

</html>